### ISSUE TITLE
已添加到“微信小程序开发资源汇总”

### ISSUE THREAD

**Issue by justjavac** [wangmingjob/weapp-weipiao#1]
我正在整理一个微信小程序开发资源汇总，已经将你的repo添加进了列表，[justjavac/awesome-wechat-weapp](https://github.com/justjavac/awesome-wechat-weapp)

非常感谢你的程序

**Comment by wangmingjob** [comment]
3Q，哈哈

**Comment by wangmingjob** [comment]
嗯嗯，3Q

**Comment by luuman** [comment]
能不能放些有诚意的作品

**Comment by johanazhu** [comment]
请问，数据接口怎么做？
